# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Status

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Populates Tickers
      run: |
        echo "MSFT" > Tickers
        echo "" >> companyanalyzer.py
        echo "save_dataframe_to_csv(companydf)" >> companyanalyzer.py
    - name: Run the script
      run: |
        python3 companyanalyzer.py
    - name: 'Upload csv Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: companies-csv
        path: companies.csv
        retention-days: 1
    - name: 'Upload excel Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: companies-xlsx
        path: companies.xlsx
        retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download script csv output
      uses: actions/download-artifact@v3
      with:
        name: companies-csv
    - name: Download script xlsx output
      uses: actions/download-artifact@v3
      with:
        name: companies-xlsx
    - shell: bash
      run: |
        test -f companies.csv
        test -f companies.xlsx
        grep "MSFT" companies.csv
  push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      REPO_NAME: ${{secrets.DOCKERHUB_REPO}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3 
      - name: Build the image
        run: |
          docker build --tag $REPO_NAME:${GITHUB_SHA::6} .
      - name: Push the image
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push $REPO_NAME:${GITHUB_SHA::6}