# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Populates Tickers
      run: |
        echo "MSFT" > Tickers
    - name: Run the script
      run: |
        python3 companyanalyzer.py
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: companies-csv
        path: companies.csv
        retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download script csv output
      uses: actions/download-artifact@v3
      with:
        name: companies-csv
    - shell: bash
      run: |
        test -f companies.csv
        grep "MSFT" companies.csv
    
